spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.1.198:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



logging:
  level:
    root: info # springBoot日志级别
    com.pyy.pyyblogdomain: debug
  file: log/blog-dev.log # 默认10M


server:
  port: 8080


